export enum ALIGNMENT {
  LEFT = 'left',
  RIGHT = 'right',
  CENTER = 'center',
  FLEX_END = 'flex-end',
  STRETCH = 'stretch',
  SPACE_BETWEEN = 'space-between',
  SPACE_AROUND = 'space-around',
  FLEX_START = 'flex-start',
  SPACE_EVENLY = 'space-evenly',
  HIDDEN = 'hidden',
  ROW = 'row',
  SMALL = 'small',
  LARGE = 'large',
  UNDERLINE = 'underline',
  ABSOLUTE = 'absolute',
  DOUBLE = 'double',
  CONTAIN = 'contain',
  LINETHROUGH = 'line-through',
}
