export const string = {
  home: 'Home',
  Login: 'Log in',
  SignUp: 'Sign Up',
  SignIn: 'SignIn',
  forgotPassword: 'Forgot password ?',
  orSignin: 'Or Sign In Using',
  orSignup: 'Or Sign Up Using',
  ADD: 'ADD',
  UPDATE: 'UPDATE',
  CANCEL: 'CANCEL',
  SelectALL: 'Select All',
  UnselectALL: 'Unselect All',
  SeeLess: 'See Less',
  SeeMore: 'See More',
  CreateAccount: 'Create new account',
};

export const InputFieldError = {
  EMPTY_EMAIL: 'please enter email address.',
  EMPTY_FIRST: 'please enter first name.',
  EMPTY_LAST: 'please enter last name.',
  VALID_EMAIL: 'please enter valid email address.',
  EMPTY_PASSWORD: 'please enter password.',
  VALID_PASSWORD: 'password must be atleast 6 character.',
  MISMATCH_PASSWORD: 'Mismatched password.',
  WANT_LOGOUT: 'Are you sure, you want to logout?',
  EMAIL_IN_USE: 'That email address is already in use!',
  EMAIL_NOT_EXIST: "Email doesn't exist, please signup now!",
};
