export const placeholder = {
  Email: 'Username,email or mobile number',
  password: 'Password',
  Confpassword: 'Confirm your password',
  username: 'Email',
  pass: 'password',
  Confpass: 'Confirm password',
  FirstName: 'Enter your First Name',
  LastName: 'Enter your Last Name',
  done: 'done',
  next: 'next',
  search: 'search products...',
  addItem: 'Add Item',
  AlertEnterName: 'Please enter the name.',
};
export const title = {
  Email: 'Email',
  SignIn: 'Sign in',
  FirstName: 'First Name',
  LastName: 'Last Name',
  HaveAnAccount: 'Have an account',
  YesContinue: 'Yes, Continue',
  NoCancel: 'No, Cancel',
  CustomPopup: 'Are you sure you want to delete',
  EzyMart: 'EzyMart',
  search: 'Search',
  EmptyCart: 'Ohh! No Cart Is Empty',
  EmptyList: 'Ohh! No Products available',
  Checkout: 'Checkout',
  ContinueShop: 'Continue Shopping',
  AddedItem: 'added itmes',
  Total: 'Total :-',
  Press: 'press',
  Name: 'Name',
  Comment: 'Comment',
  Date: 'Date',
  Delivery: 'Delivery',
  ProductDetails: 'Product Details',
  Description: 'Description',
  Weight: 'Weight',
  Dimensions: 'Dimensions',
  Height: 'Height',
  Widht: 'Widht',
  Depth: 'Depth',
  Warranty: 'Warranty',
  ReturnPolicy: 'ReturnPolicy',
  CreatedAt: 'CreatedAt',
  UpdatedAt: 'UpdatedAt',
  Barcode: 'Barcode',
  RatingReviews: 'Rating & Reviews',
};
export const tabBar = {
  home: 'Home',
  reels: 'Reels',
  chat: 'Chat',
  search: 'Search',
  profile: 'Profile',
};
export const Buttons = {
  OK: 'OK',
  CANCEL: 'CANCLE',
};
export const common = {
  Alert: 'Alert',
  loginSuccess: 'Login Success',
  signupSuccess: 'Signup Success',
  loginFailed: 'Login Failed!',
  welcome: 'Welcome to EzyMart',
};
